# Generated by Django 5.2.7 on 2026-04-28 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English')], default='uk', max_length=10)),
                ('font_family', models.CharField(choices=[('system-ui, sans-serif', 'System'), ('"Courier New", monospace', 'Monospace'), ('"Segoe UI", Roboto, sans-serif', 'Sans Serif')], default='system-ui, sans-serif', max_length=100)),
                ('theme', models.CharField(choices=[('dark', 'Темна'), ('light', 'Світла')], default='dark', max_length=20)),
                ('animations_enabled', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
