# Generated by Django 5.2.7 on 2026-05-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkshopBlock', '0002_projectfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRunConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_file', models.CharField(blank=True, help_text='Шлях до головного файлу', max_length=300, null=True)),
                ('arguments', models.TextField(blank=True, default='', help_text='Аргументи командного рядка')),
                ('python_version', models.CharField(default='3', help_text='Версія Python', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='run_config', to='WorkshopBlock.project')),
            ],
        ),
    ]
