# Generated by Django 5.2.7 on 2026-05-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkshopBlock', '0003_projectrunconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrunconfig',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('flowperl', 'FlowPerl')], default='python', max_length=20),
        ),
    ]
