# Generated by Django 5.2.7 on 2026-03-08 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudyBlock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва екзамену')),
                ('passing_score', models.PositiveIntegerField(default=80, verbose_name='Прохідний бал (%)')),
                ('reward_synit', models.PositiveIntegerField(default=100, verbose_name='Нагорода SyNit за екзамен')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='StudyBlock.course', verbose_name='Курс')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва тесту')),
                ('reward_synit', models.PositiveIntegerField(default=20, verbose_name='Нагорода SyNit за тест')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='StudyBlock.lesson', verbose_name='Урок')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст питання')),
                ('options', models.JSONField(default=dict, verbose_name='Варіанти відповідей (JSON)')),
                ('correct_option_key', models.CharField(max_length=50, verbose_name="Ключ правильної відповіді (напр. 'a')")),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ExaminationBlock.exam')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ExaminationBlock.test')),
            ],
        ),
    ]
