# Generated by Django 5.2.7 on 2026-04-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeartBlock', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
